# Generated by Django 5.2 on 2025-05-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('alternatePhoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('nin', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('bvn', models.CharField(blank=True, max_length=20)),
                ('date_date', models.DateField(auto_now_add=True)),
                ('passport_photo', models.ImageField(blank=True, upload_to='passport_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('relationship', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='customers.customer')),
            ],
        ),
    ]
